#!/usr/bin/env python3
"""
Knowledge card HTML generator for the make-knowledge-cards skill.

Reads a JSON file containing card data and produces a self-contained HTML file
with styled, printable knowledge cards.

Usage:
    python generate_cards.py <cards_json> [--output <output_html>]

JSON input format:
{
    "source_file": "document.pdf",
    "source_title": "Document Title",
    "card_count": 6,
    "cards": [
        {
            "title": "Card Title",
            "core_knowledge": "Core knowledge content.",
            "explanation": "Brief explanation.",
            "example": "Concrete example from the text.",
            "self_test": "Self-test question?",
            "summary": "Summary or deeper thinking."
        }
    ]
}
"""

import argparse
import json
import sys
from pathlib import Path

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="{lang}">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{title} - Knowledge Cards</title>
<style>
:root {{
  --bg: #f0f2f5;
  --card-bg: #ffffff;
  --primary: #2563eb;
  --primary-light: #dbeafe;
  --text: #1e293b;
  --text-muted: #64748b;
  --border: #e2e8f0;
  --accent: #f59e0b;
  --accent-light: #fef3c7;
  --green: #10b981;
  --green-light: #d1fae5;
  --purple: #8b5cf6;
  --purple-light: #ede9fe;
  --shadow: 0 2px 8px rgba(0,0,0,0.08);
}}
* {{ margin: 0; padding: 0; box-sizing: border-box; }}
body {{
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
  background: var(--bg);
  color: var(--text);
  line-height: 1.6;
  padding: 24px;
}}
.header {{
  max-width: 820px;
  margin: 0 auto 32px;
  text-align: center;
}}
.header h1 {{
  font-size: 28px;
  font-weight: 700;
  color: var(--text);
  margin-bottom: 8px;
}}
.header .meta {{
  font-size: 14px;
  color: var(--text-muted);
}}
.header .meta span {{
  display: inline-block;
  margin: 0 8px;
}}
.cards-container {{
  max-width: 820px;
  margin: 0 auto;
  display: flex;
  flex-direction: column;
  gap: 24px;
}}
.card {{
  background: var(--card-bg);
  border-radius: 12px;
  padding: 28px;
  box-shadow: var(--shadow);
  border: 1px solid var(--border);
  page-break-inside: avoid;
}}
.card-number {{
  display: inline-block;
  background: var(--primary);
  color: #fff;
  font-size: 13px;
  font-weight: 600;
  padding: 2px 12px;
  border-radius: 20px;
  margin-bottom: 12px;
}}
.card-title {{
  font-size: 20px;
  font-weight: 700;
  color: var(--text);
  margin-bottom: 20px;
  line-height: 1.4;
}}
.card-section {{
  margin-bottom: 16px;
}}
.card-section:last-child {{
  margin-bottom: 0;
}}
.card-section-label {{
  display: flex;
  align-items: center;
  gap: 6px;
  font-size: 13px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.5px;
  margin-bottom: 6px;
}}
.card-section-content {{
  font-size: 15px;
  color: var(--text);
  line-height: 1.7;
}}
.section-core .card-section-label {{ color: var(--primary); }}
.section-core {{ border-left: 3px solid var(--primary); padding-left: 14px; }}
.section-explanation .card-section-label {{ color: var(--green); }}
.section-explanation {{ border-left: 3px solid var(--green); padding-left: 14px; }}
.section-example .card-section-label {{ color: var(--accent); }}
.section-example {{ border-left: 3px solid var(--accent); padding-left: 14px; }}
.section-example .card-section-content {{
  background: var(--accent-light);
  border-radius: 8px;
  padding: 12px 14px;
  border-left: none;
}}
.section-self-test .card-section-label {{ color: var(--purple); }}
.section-self-test {{ border-left: 3px solid var(--purple); padding-left: 14px; }}
.section-self-test .card-section-content {{
  background: var(--purple-light);
  border-radius: 8px;
  padding: 12px 14px;
  border-left: none;
  font-style: italic;
}}
.section-summary .card-section-label {{ color: var(--text-muted); }}
.section-summary {{ border-left: 3px solid var(--border); padding-left: 14px; }}
.section-summary .card-section-content {{
  font-size: 14px;
  color: var(--text-muted);
}}
.no-example {{
  color: var(--text-muted);
  font-style: italic;
  font-size: 14px;
}}
.footer {{
  max-width: 820px;
  margin: 32px auto 0;
  text-align: center;
  font-size: 13px;
  color: var(--text-muted);
  padding-top: 16px;
  border-top: 1px solid var(--border);
}}
@media print {{
  body {{ background: #fff; padding: 12px; }}
  .card {{ box-shadow: none; border: 1px solid #ddd; }}
}}
</style>
</head>
<body>
<div class="header">
  <h1>{title}</h1>
  <div class="meta">
    <span>Source: {source}</span>
    <span>Cards: {count}</span>
  </div>
</div>
<div class="cards-container">
{cards_html}
</div>
<div class="footer">
  Generated by make-knowledge-cards skill
</div>
</body>
</html>"""

CARD_TEMPLATE = """<div class="card">
  <span class="card-number">Card {num}</span>
  <h2 class="card-title">{title}</h2>
  <div class="card-section section-core">
    <div class="card-section-label">Core Knowledge</div>
    <div class="card-section-content">{core_knowledge}</div>
  </div>
  <div class="card-section section-explanation">
    <div class="card-section-label">Explanation</div>
    <div class="card-section-content">{explanation}</div>
  </div>
  <div class="card-section section-example">
    <div class="card-section-label">Example</div>
    <div class="card-section-content">{example}</div>
  </div>
  <div class="card-section section-self-test">
    <div class="card-section-label">Self-Test</div>
    <div class="card-section-content">{self_test}</div>
  </div>
  <div class="card-section section-summary">
    <div class="card-section-label">Summary</div>
    <div class="card-section-content">{summary}</div>
  </div>
</div>"""


def escape_html(text):
    """Escape HTML special characters."""
    if not text:
        return ""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
        .replace("\n", "<br>\n")
    )


def generate_cards_html(data):
    """Generate HTML from card data."""
    source_title = data.get("source_title", "Knowledge Cards")
    source_file = data.get("source_file", "unknown")
    cards = data.get("cards", [])
    card_count = len(cards)

    cards_html_parts = []
    for i, card in enumerate(cards, 1):
        example_text = card.get("example", "").strip()
        if not example_text or example_text == "原文未提供示例":
            example_html = '<span class="no-example">原文未提供示例</span>'
        else:
            example_html = escape_html(example_text)

        card_html = CARD_TEMPLATE.format(
            num=i,
            title=escape_html(card.get("title", "")),
            core_knowledge=escape_html(card.get("core_knowledge", "")),
            explanation=escape_html(card.get("explanation", "")),
            example=example_html,
            self_test=escape_html(card.get("self_test", "")),
            summary=escape_html(card.get("summary", "")),
        )
        cards_html_parts.append(card_html)

    html = HTML_TEMPLATE.format(
        lang="zh",
        title=escape_html(source_title),
        source=escape_html(source_file),
        count=card_count,
        cards_html="\n".join(cards_html_parts),
    )
    return html


def main():
    parser = argparse.ArgumentParser(
        description="Generate HTML knowledge cards from JSON data."
    )
    parser.add_argument("cards_json", help="Path to JSON file containing card data")
    parser.add_argument(
        "--output", "-o", default=None, help="Output HTML file path"
    )
    args = parser.parse_args()

    json_path = Path(args.cards_json)
    if not json_path.exists():
        print(f"ERROR: JSON file not found: {json_path}", file=sys.stderr)
        sys.exit(1)

    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    html = generate_cards_html(data)

    if args.output:
        output_path = Path(args.output)
    else:
        output_path = Path("knowledge_cards.html")

    output_path.parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html)

    print(f"HTML output saved to: {output_path}", file=sys.stderr)
    print(f"Cards generated: {len(data.get('cards', []))}", file=sys.stderr)


if __name__ == "__main__":
    main()
